/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "STD_TYPES.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
int main(void)
{
	MRCC_vInitSystemCLK();
    /* Loop forever */
	MRCC_vEnableClock(AHB1, _PERIPHERAL_EN_GPIOA);
	MGPIO_vSetPinMode(_GPIOA_PORT, GPIO_PIN_5,_MODE_OUTPUT);
	//MGPIO_vPinLock(_GPIOA_PORT, GPIO_PIN_0);
	for(;;);
}
